AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure resources for this application.
Parameters:
  GroupId:
    Description: The acronym of the gorup that this service belongs to.
    Type: String
    Default: nap
  ServiceName:
    Description: The name of the service to deploy
    Type: String
Resources:
  DockerRegistry:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${GroupId}/${ServiceName}"
      # TODO: we'll want to define this when we go live, this determines who
      #       and what has access to the registry.
      # RepositoryPolicyText:
Outputs:
  Registry:
    Description: The registry where this service stores its containers.
    Value: !Ref DockerRegistry
    Export:
      Name: !Sub "${AWS::StackName}-Registry"
